### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by Gods69** [pe0mgb/SI4735-Radio-ESP32-Touchscreen-Arduino#20]
Hi,
I got thoses compilation errors... Thanks.

Arduino : 1.8.16 (Windows 7), Carte : "ESP32 Dev Module, Disabled, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 240MHz (WiFi/BT), QIO, 80MHz, 4MB (32Mb), 921600, None"

In file included from C:\Users\Gods.AMIGA\Documents\Arduino\SI473X_2.8_TFT_V3.5\SI4735_2.8_TFT_SI5351_V3.5\SI4735_2.8_TFT_SI5351_V3.5.ino:98:0:

C:\Users\Gods.AMIGA\Documents\Arduino\libraries\TFT_eSPI/TFT_eSPI.h:883:8: warning: #warning >>>>------>> TOUCH_CS pin not defined, TFT_eSPI touch functions will not be available! [-Wcpp]

       #warning >>>>------>> TOUCH_CS pin not defined, TFT_eSPI touch functions will not be available!

        ^

C:\Users\Gods.AMIGA\Documents\Arduino\SI473X_2.8_TFT_V3.5\SI4735_2.8_TFT_SI5351_V3.5\SI4735_2.8_TFT_SI5351_V3.5.ino: In function 'void setup()':

SI4735_2.8_TFT_SI5351_V3.5:989:7: error: 'class TFT_eSPI' has no member named 'setTouch'

   tft.setTouch(calData);

       ^

C:\Users\Gods.AMIGA\Documents\Arduino\SI473X_2.8_TFT_V3.5\SI4735_2.8_TFT_SI5351_V3.5\SI4735_2.8_TFT_SI5351_V3.5.ino: In function 'void loop()':

SI4735_2.8_TFT_SI5351_V3.5:1500:19: error: 'class TFT_eSPI' has no member named 'getTouch'

     pressed = tft.getTouch(&x, &y);

                   ^

C:\Users\Gods.AMIGA\Documents\Arduino\SI473X_2.8_TFT_V3.5\SI4735_2.8_TFT_SI5351_V3.5\SI4735_2.8_TFT_SI5351_V3.5.ino: In function 'void subrstatus()':

SI4735_2.8_TFT_SI5351_V3.5:2989:20: error: 'class TFT_eSPI' has no member named 'getTouch'

     presStat = tft.getTouch(&x, &y);

                    ^

C:\Users\Gods.AMIGA\Documents\Arduino\SI473X_2.8_TFT_V3.5\SI4735_2.8_TFT_SI5351_V3.5\SI4735_2.8_TFT_SI5351_V3.5.ino: In function 'bool checkStopSeeking()':

SI4735_2.8_TFT_SI5351_V3.5:3150:37: error: 'class TFT_eSPI' has no member named 'getTouch'

   return (bool) encoderCount || tft.getTouch(&x, &y);   // returns true if the user rotates the encoder or touches on screen

                                     ^

C:\Users\Gods.AMIGA\Documents\Arduino\SI473X_2.8_TFT_V3.5\SI4735_2.8_TFT_SI5351_V3.5\SI4735_2.8_TFT_SI5351_V3.5.ino: In function 'void showFirmwareInformation()':

SI4735_2.8_TFT_SI5351_V3.5:3366:20: error: 'class TFT_eSPI' has no member named 'getTouch'

     presStat = tft.getTouch(&x, &y);

                    ^

exit status 1

'class TFT_eSPI' has no member named 'setTouch'

**Comment by jalobaugh** [comment]
Did you update the Arduino libraries prior to compiling?

This line is in the readme and it's an important one:

Move the file Setup1_ILI9341.h to the root or top directory of the TFT_eSPI library. Replace the file User_Setup_Select.h in same directory by the file User_Setup_Select.h in my github. The compiler runs after that smoothly.
